// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJ7NXtN_2abqA5ukBSdjeXUALV4Tomlw',
    appId: '1:266105140472:android:8a0088976bf56e3314b70d',
    messagingSenderId: '266105140472',
    projectId: 'amanapos',
    storageBucket: 'amanapos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhQiDvTvC8E4k7DOeg29LHr9BegJ4o0g',
    appId: '1:266105140472:ios:cfb33d993e8b288914b70d',
    messagingSenderId: '266105140472',
    projectId: 'amanapos',
    storageBucket: 'amanapos.firebasestorage.app',
    iosBundleId: 'sd.amanapos.amanaPos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMw1ojPkDspSpZkWeI6ti6mTd09RuLZNQ',
    appId: '1:266105140472:web:9e806fe020edcf0614b70d',
    messagingSenderId: '266105140472',
    projectId: 'amanapos',
    authDomain: 'amanapos.firebaseapp.com',
    storageBucket: 'amanapos.firebasestorage.app',
    measurementId: 'G-9WGRL8TSJB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWhQiDvTvC8E4k7DOeg29LHr9BegJ4o0g',
    appId: '1:266105140472:ios:cfb33d993e8b288914b70d',
    messagingSenderId: '266105140472',
    projectId: 'amanapos',
    storageBucket: 'amanapos.firebasestorage.app',
    iosBundleId: 'sd.amanapos.amanaPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMw1ojPkDspSpZkWeI6ti6mTd09RuLZNQ',
    appId: '1:266105140472:web:ad9c2840c92b049114b70d',
    messagingSenderId: '266105140472',
    projectId: 'amanapos',
    authDomain: 'amanapos.firebaseapp.com',
    storageBucket: 'amanapos.firebasestorage.app',
    measurementId: 'G-KF7G5HYB3J',
  );

}